### ISSUE TITLE
Invoice as PDF

### ISSUE THREAD

**Issue by jaroslawziolkowski** [consolibyte/quickbooks-php#102]
Is it possible send request to get invoice as PDF but this library?
Link to get invoice is simple, but still I need to authorization and use same library like to others requests will be best solution.

**Comment by rnewton** [comment]
Luckily this was merged today!
https://github.com/consolibyte/quickbooks-php/pull/100

**Comment by consolibyte** [comment]
Link:
https://github.com/consolibyte/quickbooks-php/blob/master/docs/partner_platform/example_app_ipp_v3/example_invoice_pdf_get.php
