### ISSUE TITLE
Can't set InvStartDate

### ISSUE THREAD

**Issue by clariinhk** [consolibyte/quickbooks-php#104]
Hi
I am trying to create an item of type "inventory" with TrackQtyOnHand = true.

I get the error message  "As of date for initial quantity on hand is required".
I try setting $item->setInvStartDate('2016-01-01');  But it seems that the function setInvStartDate does not exist.
Same for setAssetAccountRef which is also required to create an inventory item with TrackQtyOnHand = true.

Is the creation of a tracked inventory items not supported or am I doing something wrong..?
Thanks

**Comment by JayFett** [comment]
Hello, I just added the two missing fields and tracked inventory seems to work now.  I'm not sure why setAssetAccountRef didn't work for you as that field was there already.  Let me know how it goes

**Comment by consolibyte** [comment]
Please post a working example we can use to duplicate any problems you're experiencing. Without an example, we can not help. 

The methods DO exist (because all of the methods always exist -- they are magic methods created at runtime with __set and __get), so that shouldn't be an issue here.

**Comment by consolibyte** [comment]
Closing issue, you can re-open this if you can provide some additional details.
