### ISSUE TITLE
Slow API Call

### ISSUE THREAD

**Issue by zerolfc** [consolibyte/quickbooks-php#113]
hello,

The API call is really slow. I am currently using sandbox account, so not sure whether because its what causing the slow execution.

I contacted the Quickbooks Developer and they said, it could be the API call and the library I am currently using?

this is example API request and can take up to 30 seconds to get the response:

```php
require_once 'config.php';

$AccountService = new QuickBooks_IPP_Service_Account();
$account = $AccountService->query($Context, $realm, "SELECT Id,Name,Classification,AccountType FROM Account");
```

Please advice how to optimize it.

thank you :)
ps: PHP version 5.4, Apache server 2.2 debian

**Comment by consolibyte** [comment]
Please post the XML request going out to QuickBooks, and the XML response you're getting back.
