### ISSUE TITLE
Case mismatch between loaded and declared class names

### ISSUE THREAD

**Issue by setharell** [consolibyte/quickbooks-php#119]
I am getting the following error when using the mysqli dsn:

`Case mismatch between loaded and declared class names: QuickBooks_Driver_Sql_Mysqli vs QuickBooks_Driver_SQL_Mysqli`

when I use the mysql dsn, it works but I get the warning that mysql_connect is deprecated.  I just installed the quickbooks-php package using composer.

I have also seen a similar error in this package that I fixed by changing the class name (I know, not a good idea, I just wanted to see if it would work) and it worked.  I had to change the Quickbooks/Encryption/Aes/QuickBooks_Encryption_AES class name to QuickBooks_Encryption_Aes, or else I would get the 'case mismatch' error.  

I'm wondering, have I setup something wrong?  It seems that others would have encountered these errors as well, but I can't find any other reference.

I am using PHP 5.6.16, and I don't know if this makes a difference, but I wrapped the package to work with the Symfony Framework.

**Comment by kimwue** [comment]
Similar here during upgrade from Symfony 2.3 to 2.8:

`Case mismatch between loaded and declared class names: QuickBooks_MerchantService vs Quickbooks_MerchantService`

`"knplabs/knp-paginator-bundle": "2.4.*",`

**Comment by setharell** [comment]
It looks like this error is specific to Symfony, it is thrown on line 183 of Symfony/Component/Debug/DebugClassLoader.php

`if ($name !== $class && 0 === strcasecmp($name, $class)) {
                throw new \RuntimeException(sprintf('Case mismatch between loaded and declared class names: %s vs %s', $class, $name));
            }`

So I guess the better question is: Is there a reason that the classes in this package are named without regarding the case?  I have already come across several more instances of this problem.

**Comment by kimwue** [comment]
Any suggestion on how to solve this? I'm thinking about forking this repo and fixing the case classnaming issues?

**Comment by consolibyte** [comment]
Merged a pull request to resolve this.

**Comment by kimwue** [comment]
Thanks a lot. Any information about when this will be included in a new release?

**Comment by kimwue** [comment]
There is still another case mismatch, I created a pull request: https://github.com/consolibyte/quickbooks-php/pull/132
