### ISSUE TITLE
Redefinition of parameter $action in Callbacks.php

### ISSUE THREAD

**Issue by ctroms** [consolibyte/quickbooks-php#121]
After installing via composer on a new project I'm working on, a redefinition of parameter error was thrown. callRequestHandler line 587 in Callbacks.php

Update: Also reproduced this issue with a clean install using the example_app_ipp_v3

Update: This does not appear to be an issue when I clone this github repo and use the same example. 

Update: I replaced the Callbacks.php file in the composer package with the same file from this repo and all functions that I've tested so far appear to be working as expected. It seams as though this issue is only present in the composer package.

**Comment by Synzvato** [comment]
@ctroms It's also worth noting that the code inside of your ```composer``` package runs fine on older versions of ```PHP```. This particular flaw was exposed when you pulled in ```PHP 7.0``` to run your new project on, as this latest version does not tolerate parameter redefinitions. That's the main problem.

So the code inside of the ```composer``` package is essentially incompatible with modern versions of ```PHP```, but shouldn't break on older releases. I hope these details help reproduce the issue.

**Comment by ctroms** [comment]
@Synzvato Yea. I realized that soon after my last update. I just forgot to come back here and close this issue. I just pulled in dev-master (which is fine for this particular project) rather than 3.1 and all is well. Thanks for the info.
