### ISSUE TITLE
Need help in setting v3 QBO base/gateway URL

### ISSUE THREAD

**Issue by chethank** [consolibyte/quickbooks-php#125]
Hi,
I received and email from the QB support team saying we are using QBO v2 API calls. Though I have migrated to V3 they are saying we are still making calls using V2 API and need to change our "**cluster specific v2 QBO URL to v3 QBO base/gateway URL**"
The V2 API call thats been made is "https://qbo.intuit.com/qbo1/rest/user/v2/", I checked the QB library and found that its present in "/QuickBooks/IPP.php" file line number 626.

It will be very helpful if you can let me know how to change the above URL to use V3 API.
Do I need to change the baseurl from "https://qbo.intuit.com/" to "https://quickbooks.api.intuit.com"?

Thanks
Chethan K

**Comment by jsgoyette** [comment]
We've also been contacted by Intuit support about this. A solution would be great, even if it is just a matter of updating the code manually for now.

**Comment by jsgoyette** [comment]
Okay, I believe I have resolved this for us. Apparently in our code we were calling:

`$ipp->baseURL($ipp->getBaseURL($context, $realm));`

I'm no longer sure why we were doing this, but I think this call was needed with previous versions. However, that `getBaseURL` call is not needed anymore, and now the baseURL defaults to V3.

**Comment by chethankswamy** [comment]
Thanks jsgoyette, Sorry for the delayed response, I was waiting for the reply from the QB support team to confirm that.

**Comment by chethank** [comment]
Thanks jsgoyette, Sorry for the delayed response, I was waiting for the reply from the QB support team to confirm that.

**Comment by petergarnaes** [comment]
So did you get the confirmation? Do you have the solution, can this issue be closed?

**Comment by chethank** [comment]
Yes, got the confirmation and its fine. The issue can be closed.
