### ISSUE TITLE
findAll throwing QueryParserError

### ISSUE THREAD

**Issue by petergarnaes** [consolibyte/quickbooks-php#129]
I have been tasked with updating our QuickBooks integration before the upcoming sunsetting of v2. All the examples in example_app_ipp_v3/ runs, but when running the example_app_ipp_v3/example_account_query.php with the added lines:

```
$accountsFindAll = $AccountService->findAll($Context, $realm);
if ($accountsFindAll){
	foreach ($accounts as $Account)
	{
		print('Account Id=' . $Account->getId() . ' is named: ' . $Account->getFullyQualifiedName() . '<br>');
	}
} else {
	print($AccountService->lastError());
}
```

I get:

```
4000: [Error parsing query, QueryParserError: Encountered "<EOF>" at line 0, column 0.
Was expecting:
    "select" ...
    ]
```

This maybe apply to all services, since it at least also applies to SalesTerms (I tried there as well). I could just use the query, which works fine for QuickBooks_IPP_Service_Account, except this does not work for QuickBooks_IPP_Service_SalesTerm, which only has findAll.

Anyone who knows a quick-fix?

**Comment by consolibyte** [comment]
Don't use findAll() with v3. Use ->query() instead. 
https://github.com/consolibyte/quickbooks-php/blob/master/docs/partner_platform/example_app_ipp_v3/example_account_query.php
