### ISSUE TITLE
Can't load file ItemGroupDetail

### ISSUE THREAD

**Issue by gmuresan** [consolibyte/quickbooks-php#131]
I'm getting an error message for one of my users about a missing required file ItemGroupDetail. He is using a non US version of QuickBooks Online.

Where would I need to add this file?

Here is the stack trace

`object(Symfony\Component\Debug\Exception\FatalErrorException)#4506 (8) { ["message":protected]=> string(301) "QuickBooks_Loader::load(): Failed opening required '/home/forge/default/vendor/consolibyte/quickbooks/QuickBooks/IPP/Object/ItemGroupDetail.php' (include_path='/home/forge/default/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/php:/usr/share/pear:/home/forge/default/vendor/consolibyte/quickbooks')" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(64) ["file":protected]=> string(71) "/home/forge/default/vendor/consolibyte/quickbooks/QuickBooks/Loader.php" ["line":protected]=> int(56) ["trace":"Exception":private]=> array(1) { [0]=> array(4) { ["function"]=> string(14) "handleShutdown" ["class"]=> string(28) "Illuminate\Exception\Handler" ["type"]=> string(2) "->" ["args"]=> array(0) { } } } ["previous":"Exception":private]=> NULL ["severity":protected]=> int(0) }`

**Comment by marabesi** [comment]
That's right, I'm facing the same issue.

I have a clue why this is happening and I'll try to do the fix asap
