### ISSUE TITLE
Update any objects

### ISSUE THREAD

**Issue by marabesi** [consolibyte/quickbooks-php#137]
Is there a way to update many products at once ?

I need to update many products data at once and to do it one by one is something weird, is there a better way ?

**Comment by consolibyte** [comment]
Intuit's APIs support a "batch" request, but we have not implemented support for this yet.

**Comment by marabesi** [comment]
Do you have any link that I can follow ? I saw a lot of XML examples in how to do a batch request but I couldn't find any with the request

**Comment by consolibyte** [comment]
Our library does not support batch requests, so no, I do not have an example. 

If you'd like to implement it, you can refer to Intuit's documentation:
https://developer.intuit.com/docs/api/accounting/batch
