### ISSUE TITLE
Forums offline for maintenance

### ISSUE THREAD

**Issue by attndeficit** [consolibyte/quickbooks-php#138]
The forums are still "down for maintenance tonight"...(have been down for several days now)... any ETA when they might be back online?  google results direct there often and the only way to view is to try a cached version, which works... if the forums are broken or are going to be down for an extended period of time, can you put a read-only version online so this information is searchable/browseable?

http://consolibyte.com/forum/

Thank you for this project :)

**Comment by Brandon1811** [comment]
I'm also wondering when the consolibyte forums will be back up...  Thanks in advance! :)

**Comment by sandstones** [comment]
I've also noticed that the consolibyte web pages have been edited to remove all links to this github repository.  I'm thinking that they are pulling back from supporting this.

**Comment by consolibyte** [comment]
Uh, nope. You're thinking wrong. More like the forums were getting constantly attached by russian spam bots, and we need to re-think how we validate accounts so that we don't have to manually delete 10,000+ russian spam posts a day.

**Comment by sandstones** [comment]
My apologies re: the forum.   But is there a way to have the forum contents available for search even if posting is disabled?

On the pages, I am virtually certain that yesterday I was at [http://consolibyte.com/downloads/quickbooks-php-devkit/]  and it did not have the links to github.  I spent about 5 minutes clicking and going around in circles, but could not find such a link.  But they are clearly there now, don't have any idea what is different.

**Comment by CaptainHypertext** [comment]
@consolibyte Have you tried [reCaptcha 2](https://www.google.com/recaptcha/intro/index.html)?  It worked really well for my forums in dealing with that problem.

**Comment by krisred** [comment]
@consolibyte  Any ETA on when the forums will be back online.

**Comment by CaptainHypertext** [comment]
NEVAH!!
No really, it's been several months, so I'm guessing he just shut them down.

**Comment by attndeficit** [comment]
Thank you @consolibyte for bringing these back online.  It appears you may still be battling bots or other issues as I'm getting timed out consistently but I was able to search in there a little bit today without using the waybackmachine.

I appreciate your work... your library really makes life in a quickbooks-dependent-business suck a lot less... mysql mirror working great !
