### ISSUE TITLE
Error while using token & token_secret

### ISSUE THREAD

**Issue by noisyox** [consolibyte/quickbooks-php#139]
The token & token_secret generated by consolibyte/quickbooks-php is not authorized while using with rest client / postman. 

gives response:
message=ApplicationAuthenticationFailed; errorCode=003200; statusCode=401

help. thanks in advance.

**Comment by consolibyte** [comment]
Please show the request you're making with postman. 

Also, did you generate your token in SANDBOX mode, or for a LIVE company?

**Comment by noisyox** [comment]
Yes token is generated in sandbox mode, how does the mode effect the usage? I am using development keys to generate token.

What's the difference between oauth_request_token & oauth_access_token in quickbooks_oauth table?

[qbo.postman_collection.json.zip](https://github.com/consolibyte/quickbooks-php/files/542361/qbo.postman_collection.json.zip)

**Comment by consolibyte** [comment]
OK, so I see at least two problems: 

1. Your OAuth token looks highly suspect. Where did you get it? It looks like you may have copied the ENCRYPTED value straight from the database, instead of using the actual, unencrypted value. 
2. You're trying to use a SANDBOX token, with a LIVE QuickBooks Online account. They are two separate environments, so this won't work.

**Comment by noisyox** [comment]
1. I have tried both the sets but gives the same response.
2. I am using it with a sandbox account, the company id is of sandbox. should i use the sandbox url for rest client?

**Comment by consolibyte** [comment]
You need to use the UNENCRYPTED OAuth tokens. You can read about request tokens in the OAuth spec. 

Yes, you need to use the SANDBOX URLs with the SANDBOX QuickBooks companies, and the LIVE URLs with the LIVE QuickBooks companies.

**Comment by noisyox** [comment]
Is there a function in the sdk to de-crypt the token can you shoe me the file, rest i'll work.

**Comment by consolibyte** [comment]
Try doing this: 
https://github.com/consolibyte/quickbooks-php/blob/master/docs/partner_platform/example_app_ipp_v3/diagnostics.php

**Comment by noisyox** [comment]
Thanks a lot, it works. I just needed to decrypt the token, works with same url.

I just need one more thing what is default access duration of the generated token, can I pass custom time? if yes what is the longest duration that can be passed.

**Comment by consolibyte** [comment]
http://lmgtfy.com/?q=quickbooks+online+oauth+token+expiration
