### ISSUE TITLE
Auth methods

### ISSUE THREAD

**Issue by marabesi** [consolibyte/quickbooks-php#146]
Hello guys,

I was wondering if exists a other type to authenticate the user (without the popup).

I'd like to implement a feature to send invoices in a automated way (without the user input). Something like, the user login once and I just send as many invoices as I want to.

Is it possible ?

**Comment by consolibyte** [comment]
This is exactly what the default examples do: 

`the user login once and I just send as many invoices as I want to.`

If you're not seeing that behavior, then you messed up your configuration.
