### ISSUE TITLE
Getting error after click on connect to quickbook button

### ISSUE THREAD

**Issue by javaidTa** [consolibyte/quickbooks-php#147]
after doing the complete configuration when i run the index.php using PHP SDK from github after clicking on connect to quickbook button it gives me the following error

Oops! An error has occurred.
Please close this window and try again. 

Error Code: internal_error 
Message: Error getting application from request token

You can contact us for further assistance. Error Id:ixnkryec2iu513ef45f3f5xv-66016491

Your help will be appreciated

**Comment by consolibyte** [comment]
This was already responded to on StackOverflow. Posting on 40,000 message boards will not help you get a response any quicker, so please stop doing that. 

See the comments on your StackOverflow post.
