### ISSUE TITLE
Use of undefined constant QUICKBOOKS_OBJECT_XML_DROP

### ISSUE THREAD

**Issue by erictompkins** [consolibyte/quickbooks-php#15]
I'm getting an error notice that is interferring with output the XML. 

Notice: Use of undefined constant QUICKBOOKS_OBJECT_XML_DROP - assumed 'QUICKBOOKS_OBJECT_XML_DROP' in quickbooks/QuickBooks/QBXML/Object/InventoryItem.php on line 372

I did a quick search and the variable QUICKBOOKS_OBJECT_XML_DROP shows up in 46 files. 

In this particular case it's in the method parameters. 

```
public function asQBXML($request, $todo_for_empty_elements = QUICKBOOKS_OBJECT_XML_DROP, $indent = "\t", $root = null)
{
}
```

I think that the correct usage would be something like 

```
public function asQBXML($request, $todo_for_empty_elements = QuickBooks_QBXML_Object::XML_DROP, $indent = "\t", $root = null, $parent = null)
{
}
```

That is based on quickbooks/QuickBooks/QBXML/Object/Check.php line 498.

**Comment by SoLoGHoST** [comment]
This problem still exists for EstimateAdd:  Example:

` $Estimate->asQBXML(QUICKBOOKS_ADD_ESTIMATE);`

Estimate.php looks like this:

`public function asQBXML($request, $todo_for_empty_elements = QUICKBOOKS_OBJECT_XML_DROP, $indent = "\t", $root = null, $parent = null)`
