### ISSUE TITLE
Json or Soap(XML)

### ISSUE THREAD

**Issue by rickbeacham** [consolibyte/quickbooks-php#154]
I'm curious if your going to start using json instead of Soap for V3 of quickbooks online API?  I'm guessing Soap is for the desktop version?  Is Soap sufficient for importing Sales Orders onto QB online?  I'm new to SOAP requests and the quickbooks API v3 seems to use json now.  

Good work by the way.

**Comment by consolibyte** [comment]
QuickBooks Online does not use SOAP.
QuickBooks Online uses XML (the actual REST API also supports JSON, but we only support XML right now). 

QuickBooks desktop does not use SOAP either. 
QuickBooks desktop uses XML (a schema colloquially called qbXML).
The Web Connector uses SOAP (but it's just a container for the qbXML requests and requires zero SOAP knowledge to utilize).

At some point we'd like to support JSON and XML, but for right now we only support XML. There's really no advantage/disadvantage to either, and Intuit supports both equally well.
