### ISSUE TITLE
mcrypt is deprecated in PHP 7

### ISSUE THREAD

**Issue by zackkrida** [consolibyte/quickbooks-php#158]
In the `Quickbooks/Aes.php` file you are using `mcrypt` for encryption. 

https://github.com/consolibyte/quickbooks-php/blob/master/QuickBooks/Encryption/Aes.php#L34

[`Mcrypt`has been deprecated in PHP 7.1 in favor of openSSL](http://php.net/manual/en/migration71.deprecated.php).

OSX users working locally may want to `brew install php71-mcrypt`.
On Ubuntu you'll want to `sudo apt-get install php7.1-mcrypt`
Or via yum with ` yum install php71-php-mcrypt`

**Comment by nateajohnson** [comment]
Is there a way to ignore the warnings then? I get this:

Function mcrypt_module_open() is deprecated

It looks like warnings are turned on STRICT all through this library.

**Comment by nateajohnson** [comment]
I added this to the top of the file I am calling and it seems to work:

error_reporting(E_ALL &~ E_DEPRECATED);

That said, once PHP removed mcrypt support, this library will stop working.

**Comment by zettich** [comment]
mcrypt is deprecated in 7.1
you should add a dependency for this in composer.json to meet PHP < 7.1

**Comment by CaptainHypertext** [comment]
Was this issue ever solved in a patch or something?

**Comment by marabesi** [comment]
UP

**Comment by webdevsoup** [comment]
Going to bump this.  I ran in to this error today.  Trying to run on my Docker installation, and mcrypt is deprecated from php7.1, and completely removed in php7.2.

**Comment by rps-repo** [comment]
While mcrypt was removed from PHP 7.2 it can still be installed via PECL.  Not a long term solution though.  I have no idea what is involved with adding openssl support to this framework but I suspect its not trivial since it would need to support both mcrypt and openssl.  Otherwise, only supporting openssl would break current installations.

**Comment by bryonbean** [comment]
I'm wondering if anyone using this package with php 7.2 has tried [phpseclib's mcrypt shim](https://github.com/phpseclib/mcrypt_compat) instead of installing mcrypt. It seems like it should work as it supports Rijndael 256; thoughts?

**Comment by bryonbean** [comment]
Sorry, I didn't see this in the README of phpseclib's mcrypt shim:

> Although `nofb` is supported `ofb` is not.

The file mentioned in the OP uses `ofb`, though it may be trivial to switch to `nofb`? Not sure.

**Comment by amirshawn** [comment]
I'm curious if anyone has figured out a good way to get around this without editing any of the package files?

**Comment by gsalmon** [comment]
BUMP.
Heres a workaround: http://www.netsuite.com

**Comment by aik099** [comment]
Any update on this?

The mcrypt installed via PECL on PHP 7.2 works, but I have tons of warning. Not sure if PECL would save the day on PHP 7.3 or later.

**Comment by consolibyte** [comment]
We'll be making some updates here soon (we generally follow Debian stable releases, so because Debian hasn't had PHP 7.2 yet -- they will in July) we haven't made updates here yet.

**Comment by galapogos01** [comment]
#228

**Comment by zackkrida** [comment]
As I'm not using this library anymore I'd like to close it and direct folks to the other relevant issue #228. Thanks all!
