### ISSUE TITLE
updating records not working 

### ISSUE THREAD

**Issue by opensourcecrm** [consolibyte/quickbooks-php#159]
Hi 
The API is updating first 25 row records but other rows were not updating its failing to create an customer object to other row information.  below is the code sample to check if i am doing anything wrong.
require_once dirname(__FILE__) . '/config.php';
foreach($csv as $row)
{
var_dump($row);
$CustomerService = new QuickBooks_IPP_Service_Customer();
$customers = $CustomerService->query($Context, $realm, "SELECT * FROM Customer WHERE Id='".$row[0]."' ");
$Customer=$customers[0];
	$PrimaryPhone = new QuickBooks_IPP_Object_PrimaryPhone();
    $PrimaryPhone->setFreeFormNumber($row[2]);
    $Customer->setPrimaryPhone($PrimaryPhone);
	$CustomerService->update($Context, $realm, $Customer->getId(), $Customer);
}

**Comment by consolibyte** [comment]
Please post the XML request you're sending to QuickBooks, and the XML response you're getting back that shows the failure.

**Comment by opensourcecrm** [comment]
How to check the XML request. I am using your wrapper class and invoking the QuickBooks_IPP_Service_Customer object.

**Comment by consolibyte** [comment]
Look at the examples: 
https://github.com/consolibyte/quickbooks-php/blob/master/docs/partner_platform/example_app_ipp_v3/debugging.php
