### ISSUE TITLE
Quickbook data fetch error

### ISSUE THREAD

**Issue by saadjawaid** [consolibyte/quickbooks-php#165]
Hi, Im trying to fetch invoices from quickbooks. Im using PHP Phalcon as the platform, and I was fetching data in the form of cron job. It was working fine till 2 months back and all of a sudden it stopped working. Now when Im trying to access the cron link I get following error:

Fatal error: Call to a member function IPP() on a non-object in /MY_PATH/vendor/consolibyte/quickbooks/QuickBooks/IPP/Service.php on line 829

**Comment by consolibyte** [comment]
What's your code look like? Are you authentication tokens valid? Did you look at the included debugging examples and attempt anything yet? What do the XML request/response look like? 
https://github.com/consolibyte/quickbooks-php/blob/master/docs/partner_platform/example_app_ipp_v3/debugging.php

**Comment by saadjawaid** [comment]
Was authorization issue, tried to authorize it again, and it works fine now.
