### ISSUE TITLE
Error in QuickBooks_Loader::Load() after upgrading to PHP 5.6-30

### ISSUE THREAD

**Issue by Eiriksmal** [consolibyte/quickbooks-php#167]
Our server's on 5.6.26 and the library works like a charm. I upgraded to 5.6.30 this morning to get the security and bug fixes contained in minor versions 5.6.27->5.6.30, and the library will no longer load!

Not really sure what changed to break it. I'm lost as to what's happening:
Error:
```
PHP Fatal error:  require_once(): Failed opening required '.../libraries/quickbooks-php-master/QuickBooks/Driver/.php' in .../libraries/quickbooks-php-master/QuickBooks/Loader.php on line 56
```

It successfully loads a lot of files, then appears to die when trying to load `/QuickBooks/Driver/Mysqli.php`, if I'm not mistaken.

It looks like the usual order, from observing the same code running under PHP 5.6.26, is Utilities -> Factory -> Mysqli -> Sql -> Driver. Running under PHP 5.6.30 it tries loading: Utilities -> Factory -> `loading file [/QuickBooks/Driver/.php]`. 

Adding a backtrace to Loader.php running PHP 5.6.26 shows:
```
When loading Mysqli.php:
	1) [main]
	2) (our function that intializes Quickbooks)
	3) .../QuickBooks/Utilities.php(628): QuickBooks_Utilities::driverFactory('mysqli://[redact]...', Array)
	4) .../QuickBooks/Utilities.php(232): QuickBooks_Driver_Factory::create('mysqli://[redact]...', Array, Array, 1)
	5) .../QuickBooks/Driver/Factory.php(95): class_exists('QuickBooks_Driv...')
	6) [internal function]: spl_autoload_call('QuickBooks_Driv...')
	7) [internal function]: QuickBooks_Loader::__autoload('QuickBooks_Driv...')

Loading Driver.php
	1) [main]
	2) (our function that intializes Quickbooks)
	3) ...quickbooks-php-master/QuickBooks/Utilities.php(628): QuickBooks_Utilities::driverFactory('mysqli://[redact]...', Array)
	4) ...quickbooks-php-master/QuickBooks/Utilities.php(232): QuickBooks_Driver_Factory::create('mysqli://[redact]...', Array, Array, 1)
	5) ...quickbooks-php-master/QuickBooks/Driver/Factory.php(95): class_exists('QuickBooks_Driv...')
	6) [internal function]: spl_autoload_call('QuickBooks_Driv...')
	7) [internal function]: QuickBooks_Loader::__autoload('QuickBooks_Driv...')
	8) ...quickbooks-php-master/QuickBooks/Loader.php(120): QuickBooks_Loader::load('/QuickBooks/Dri...', false)
	9) ...quickbooks-php-master/QuickBooks/Loader.php(72): require_once('/srv/www/[redact]...')
	10) ...quickbooks-php-master/QuickBooks/Driver/Sql/Mysqli.php(31): QuickBooks_Loader::load('/QuickBooks/Dri...', false)
	11) ...quickbooks-php-master/QuickBooks/Loader.php(72): require_once('/srv/www/[redact]...')
	12) ...quickbooks-php-master/QuickBooks/Driver/Sql.php(367): spl_autoload_call('QuickBooks_Driv...')
	13) [internal function]: QuickBooks_Loader::__autoload('QuickBooks_Driv...')
```

Packages affected in Amazon Linux / Redhat Linux:

```
 php56                  x86_64         5.6.26-1.129.amzn1
 php56-bcmath           x86_64         5.6.26-1.129.amzn1
 php56-cli              x86_64         5.6.26-1.129.amzn1
 php56-common           x86_64         5.6.26-1.129.amzn1
 php56-gd               x86_64         5.6.26-1.129.amzn1
 php56-mbstring         x86_64         5.6.26-1.129.amzn1
 php56-mcrypt           x86_64         5.6.26-1.129.amzn1
 php56-mysqlnd          x86_64         5.6.26-1.129.amzn1
 php56-pdo              x86_64         5.6.26-1.129.amzn1
 php56-process          x86_64         5.6.26-1.129.amzn1
 php56-xml              x86_64         5.6.26-1.129.amzn1
 php56-xmlrpc           x86_64         5.6.26-1.129.amzn1
```

Again, touching none of our/your code and reverting those 12 packages back to 5.6.26 lets the code work again. This was observed under our code at the time, a clone of this repo from mid-October, and again under the latest code, from a clone taken this morning.

Any ideas?

**Comment by Eiriksmal** [comment]
Also, to be sure I wasn't crazy, I did the same PHP package update on a separate server and got the same behavior. It's definitely something in a minor update of PHP (or the PHP MySQL native driver library?) that's now causing quickbooks-php to choke.

**Comment by rps-repo** [comment]
This may or may not help but I had a similar issue recently.  I found that special characters in the database password was causing it to fail.  I has something to do with how the framework assembles the connection string.  I found this because I have several different databases using the framework and some worked and some didn't.  After I changed the DB password to a alphanumeric only value everything began to work OK.

**Comment by Eiriksmal** [comment]
That's pretty unsettling. Though our password has special characters in it, it was working fine before upgrading the packages.

**Comment by consolibyte** [comment]
Does it have special characters that should normally be URL encoded? 

Potentially relevant code here:
https://github.com/consolibyte/quickbooks-php/blob/master/QuickBooks/Utilities.php#L54

**Comment by Eiriksmal** [comment]
It does, yeah. Any ideas what would have changed from PHP 5.6.26 to .30 that would cause the special character to start acting up?

**Comment by consolibyte** [comment]
Not a clue. But if you just `urlencode` the characters in your $dsn string, that will probably fix it.

**Comment by Eiriksmal** [comment]
Brilliant! That fixed it, thanks so much Keith/@rps-repo!

Is that in the docs somewhere that I've missed?
