### ISSUE TITLE
example_web_connector_import.php gives me "No Registered Functions"

### ISSUE THREAD

**Issue by f15radar** [consolibyte/quickbooks-php#169]
I am trying to understand this.  I finally got my passwords and usernames figured out.  Those are the only lines I have changed.  But when I use the web connect I am getting several "No registered functions" errors.  One is HostImport.  Your forums site has been spammed so I am unable to look for help there.  Can you tell me why I might be getting these errors from the example?

**Comment by consolibyte** [comment]
Post your code.

**Comment by f15radar** [comment]
Here it is.  I commented out some functions 
[example.php.txt](https://github.com/consolibyte/quickbooks-php/files/949196/example.php.txt)

**Comment by f15radar** [comment]
I think I got it.  It turns out there was left over "stuff" in the MySQL table.  Once I cleared it out, I can now import the records.  Thanks for your hard work in building this helpful tool.
