### ISSUE TITLE
Adding a TermRef to a Vendor

### ISSUE THREAD

**Issue by kdimitrov** [consolibyte/quickbooks-php#172]
Hey,

First of all thanks for the API.

I have an app which is synchronizing vendors to QuickBooks Online. I've been able to synchronize those flawlessly but unfortunately I did not succeed in adding TermRef to vendors. I tried in multiple ways but none of those worked. For example this does not work:

``$vendor->setTermRef('{-5}');``

I also tried like that:

``$terms = new QuickBooks_IPP_Object_SalesTerm();
$terms->setValue(-5);
$terms->setName('Net 10');``

and like that

`` $vendor->setTermRef(5); ``

Is there a way to get this done ? Can you give me directions and shed a light on the proper way/usage of the TermRef on a Vendor ?

Regards,

**Comment by consolibyte** [comment]
`->setTermRef(...)` is the correct method.

Please post the XML request sent to QuickBooks, and the XML response you got back. Without that, there's nothing I can do to help.

**Comment by kdimitrov** [comment]
Thanks for the prompt reply. I already figured it out. 
I was doing it like that:

``$vendor->setTermRef('{-5}');``

which did not work. However, this works:

``$vendor->setTermRef(5);`` 

where 5 is the id of the TermRef.
