### ISSUE TITLE
Is this lib dead?

### ISSUE THREAD

**Issue by zackkrida** [consolibyte/quickbooks-php#174]
There is currently limited response to issues, and an official PHP SDK being worked on here: https://github.com/intuit/QuickBooks-V3-PHP-SDK

Since this package already *doesn't support PHP 7.1 or above (see: https://github.com/consolibyte/quickbooks-php/issues/158) I fail to see it as a solution for future projects.

**Comment by consolibyte** [comment]
It *does* support PHP 7.1. `mcrypt` is deprecated, but does still work. We're working on a replacement for `mcrypt` as well. 

With that said, you're welcome to use whatever SDK you'd like to.

**Comment by mgkimsal** [comment]
OT but @consolibyte - please keep up the good work.  I can't get heads or tails out of sage integration, and have a client that is probably having to move to quickbooks.  They avoid the cloud, and your lib is the only thing that provides any sanity when trying to interact with desktop quickbooks.  The intuit PHP SDK doesn't even seem to acknowledge desktop exists - their libs (and many/most others I see for any accounting stuff) is 100% cloud based.  :/

**Comment by anotherZero** [comment]
@consolibyte I saw your comment about supporting PHP 7.1 and I wanted to see if you could clarify the impact that the ereg calls might have since they're removed from PHP 7.0+

Thank you
