### ISSUE TITLE
QB OAuth 2 support

### ISSUE THREAD

**Issue by rajkumargohan** [consolibyte/quickbooks-php#181]
Quickbooks OAuth 2 has been released. Can you please let me know when it will be added ?

https://developer.intuit.com/hub/blog/2017/07/17/oauth-2-0openid-connect-now-available-new-developers

**Comment by joelmora360** [comment]
![screenshot 1 m](https://user-images.githubusercontent.com/718447/28497930-db7bda06-6f60-11e7-84fa-996bee44c479.png)

source: https://developer.intuit.com/docs/0100_quickbooks_online/0100_essentials/000500_authentication_and_authorization/connect_from_within_your_app

**Comment by m3Lvs** [comment]
Hello Sir.. @joelmora360  I am creating an app with this plugin and the aim is to connect multiple quickbook accounts/company to it, so as of now I am currently connected to 1 account(company) with oauth 1.0a from this plugin.. is it possible to add oauth 2.0 functionality to my current code while retaining the original code for oauth 1.0 too.. also is it possible to implement what I aim to do with my app using this framework? thanks for the thoughts

**Comment by consolibyte** [comment]
Initial information on OAuth 2.0 migration from OAuth 1.0 published is here: 
https://github.com/consolibyte/quickbooks-php#oauth-10-to-oauth-20-migration

**Comment by consolibyte** [comment]
The 3.6 release has working OAuth v2.0 support now. OpenID Connect and an automated OAuth v1 to v2 migration process are coming soon.

https://github.com/consolibyte/quickbooks-php/releases/tag/v3.6

Manual migration (e.g. you have to reconnect via the OAuth flow) instructions are here:
https://github.com/consolibyte/quickbooks-php/blob/master/README_OAUTHV1_TO_OAUTHV2.md

ALSO -- Migrate your app to OAuth 2.0 before May 31 and you could win a limited edition Intuit hoodie, PLUS if you tell Intuit about your migration plans, you’ll gain entry to win the entertainment system of your dreams. Find out more here: https://intuit.me/OAuth2
