### ISSUE TITLE
Query Invoices by CustomField

### ISSUE THREAD

**Issue by Metzen2k** [consolibyte/quickbooks-php#182]
Hi,

I can query invoices using:
    $currentInvoicesReturn = $InvoiceService->query($Context, $realm, "SELECT * FROM Invoice WHERE CustomerRef = '123' ORDER BY Id ");

However, I have CustomField3 defined as "Project", with values like 'D1234'.  

How can I query for invoices WHERE CustomerRef = '123' AND CustomField3 = 'D1234'?

I've tried CustomField3, Custom3, Project, and many others, without success.

Thanks!

**Comment by consolibyte** [comment]
QuickBooks does not support what you're trying to do. 

Read the documentation: 
https://developer.intuit.com/docs/api/accounting/invoice
https://developer.intuit.com/docs/0100_quickbooks_online/0300_references/0000_programming_guide/0050_data_queries

If something is usable in a WHERE clause, it is marked as "filterable" in the documentation.
