### ISSUE TITLE
Deleting a line

### ISSUE THREAD

**Issue by turbo2ltr** [consolibyte/quickbooks-php#187]
It's a shame that the consolibyte forum has been completely destroyed with spam and the search doesn't work anymore.  So I'm posting here..

Is there a way to delete line items off a sales receipt in quickbooks XML?  I see `<SalesReceiptLineMod>` but I don't see how to just completely remove a particular TxnLineID.  Is that just not possible?

**Comment by rps-repo** [comment]
When you mod a sales receipt (or invoice) you send QB all the lines you want on a receipt.  So if you do not include the one you want removed then it will also be removed from the receipt in QB.

**Comment by turbo2ltr** [comment]
Got it working, thanks!
Just for clarification for others, I just included the TxnLineId of the lines I wanted to keep.  I wasn't sure if I would have to include all the data, but you dont.

i.e. 
```
<SalesReceiptLineMod >
	<TxnLineID >C1633-1508949116</TxnLineID>
</SalesReceiptLineMod>
<SalesReceiptLineMod >
	<TxnLineID >C164C-1508949116</TxnLineID>
</SalesReceiptLineMod>
