### ISSUE TITLE
Quickbook connection issue

### ISSUE THREAD

**Issue by xyzgd** [consolibyte/quickbooks-php#189]
I got below error, please provide solution

 Call to a member function getCompanyName() on a non-object in.....

**Comment by consolibyte** [comment]
Post your code.

**Comment by xyzgd** [comment]
I have used https://github.com/consolibyte/quickbooks-php code and get error in below link

https://github.com/consolibyte/quickbooks-php/blob/master/docs/partner_platform/example_app_ipp_v3/index.php#L95

and also I was tried with new account but my old account is used oauth 1 and my new account is oauth 2 that's why not getting consumer key and consumer secret key

I didn't get success in both options, please help.

**Comment by xyzgd** [comment]
Hi,

 I am using https://github.com/consolibyte/quickbooks-php, but I have after
created quickbook account using oauth2 I didn't get App Token, Oauth
consumer key and Oauth consumer secret but getting Client ID and Client
Secret. is it possible using Client ID and Client Secret keys can I use
consolibyte/quickbooks-php code? I am waiting for your response.

Thanks,

Jayshri
