### ISSUE TITLE
mobile, isEcommerce required on February 1, 2018, for QuickBooks Payments

### ISSUE THREAD

**Issue by emilebourquin** [consolibyte/quickbooks-php#195]
Per emails from Intuit Developer, mobile and isEcommerce (contained in context) will be required, on February 1, 2018, for QuickBooks Payments charges and refunds. The QuickBooks  Sandbox currently requires them.

As a quick hack, I added:

`$payload['context'] = array('mobile' => FALSE, 
                                  'isEcommerce' => FALSE);`

to the _chargeOrAuth function in QuickBooks/Payments.php

**Comment by consolibyte** [comment]
Examples:
https://github.com/consolibyte/quickbooks-php/blob/master/docs/payments/example_creditcard_contexts.php

**Comment by consolibyte** [comment]
As an example of how to use this with the recently committed code:

```
$context = array(
	// This indicates that it is a payment made from a MOBILE DEVICE (phone, tablet, etc.)
	'mobile' => true,       // defaults to FALSE
	// This indicates that it is a RECURRING payment
	'recurring' => true,    // defaults to FALSE
	// This indicates it's an e-commerce payment (made online)
	'isEcommerce' => true,  // defaults to FALSE 
	);
if ($Transaction = $Payments->charge($Context, $CreditCard, $amount, $currency, $context))
{
	//print_r($Transaction);
	print('Id: ' . $Transaction->getId() . '<br>');
	print('Auth Code: ' . $Transaction->getAuthCode() . '<br>');
	print('Status: ' . $Transaction->getStatus() . '<br>');
}
```

**Comment by cgeorgiev** [comment]
Hello,
What about MerchantService.php and the usage of QuickBooks_MerchantService and QuickBooks_MerchantService_CreditCard - can you provide a fix for them too? Thanks a lot.

**Comment by kimwue** [comment]
Please reopen because of cgeorgiev comment.
Thanks.
