### ISSUE TITLE
All methods

### ISSUE THREAD

**Issue by AndreyNazarchuk** [consolibyte/quickbooks-php#199]
Where can I find all of the available methods as QuickBooks accepts them in the invoices, for example, SetTxnDate and stuff like that?

**Comment by consolibyte** [comment]
QuickBooks ONLINE, or QuickBooks FOR WINDOWS?

**Comment by AndreyNazarchuk** [comment]
Nevermind I found that if I create one in online and query it in PHP I can see the fields used.
