### ISSUE TITLE
 How many new projects are using PHP < 5.3?

### ISSUE THREAD

**Issue by mastermatt** [consolibyte/quickbooks-php#2]
The next logical step for the development of the devkit would be to add [PSR compliance](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md). This of course would mean namespacing the module.  

The pros for this change would be:
- Increased efficiency, as classes would be lazy loaded on a need be bases.
- Better organization without the worry of name collisions with other libraries.
- It will increase the ease of use for developers who are not contributing to the project, but simply using it in their own project.  

The downside would be changing the required PHP from 5+ to 5.3+. Which leads back to the question in the title, how many new projects are using PHP <5.3?  

I'm writing this post in an attempt to get a healthy debate going on the topic, so throw in your two cents.

**Comment by drmjo** [comment]
+1 for namespaces
+1 for PSR

**Comment by kgustine** [comment]
I have a few open sites with webhostingbuzz.  I can actually choose which PHP version I want to use from the cPanel.  I can choose between 4.4, 5.2, 5.3, 5.4, and 5.5.

With that in mind. I only use the framework on an in house server, so I welcome the updates!

**Comment by maxolasersquad** [comment]
+1 in 2016 for PSR namespacing. Anyone on an older version of PHP can always use a tagged release without the PSR classloading (assuming that the version before PSR feature still works with the latest Quickbooks API in the future.)
