### ISSUE TITLE
Pdo.php doesn't exist

### ISSUE THREAD

**Issue by webdevsoup** [consolibyte/quickbooks-php#200]
Just implemented this, and after getting it all set up, upon first attempt, I get an error that the require_once for the Pdo.php file doesn't exist.

```
Warning: require_once(/var/www/html/_include/quickbooks-php-master-payments/QuickBooks/Driver/Pdo.php): failed to open stream: No such file or directory in /var/www/html/_include/quickbooks-php-master-payments/QuickBooks/Loader.php on line 56

Fatal error: require_once(): Failed opening required '/var/www/html/_include/quickbooks-php-master-payments/QuickBooks/Driver/Pdo.php' (include_path='.:/usr/local/lib/php:/var/www/html/_include/quickbooks-php-master-payments') in /var/www/html/_include/quickbooks-php-master-payments/QuickBooks/Loader.php on line 56
```

**Comment by webdevsoup** [comment]
nevermind, my stupidity in setting up config..... Closing.

**Comment by consolibyte** [comment]
I'd love to see a pull request for this if you have it! Or even just a blobl of code I can merge in.

**Comment by webdevsoup** [comment]
No pull request, it was a configuration error on my own part within config.php.  However, I am having another issue where $Context isn't defined.
