### ISSUE TITLE
Switch from mysql to mysqli

### ISSUE THREAD

**Issue by wiatrp** [consolibyte/quickbooks-php#211]
I recently upgraded my server to php7 and all my mysql calls are not working. I have web connector functions like the ones in [this file](https://github.com/consolibyte/quickbooks-php/blob/master/docs/web_connector/example_app_web_connector/functions.php). In php7 these mysql calls will not work. 

I changed my dsn to a mysqli connection and I can connect to my db but obviously these calls are not included in php. My problem is mysqli_query() requires the connection as part of the call and I can't figure out if I can access that variable from the functions.

**Comment by consolibyte** [comment]
You can use global variables. You can put your functions in a class.  You can use a helper class (probably a singleton) to establish a connection to the database and get an instance of it. 

There are many ways to do this.

**Comment by benhadad** [comment]
Does this mean if you have Php7 that the mysql drive no longer works?

**Comment by benhadad** [comment]
Another github user submitted a wrapper 
https://gist.github.com/rubo77/1db052edd8d723b59c79790b42635f1e

**Comment by consolibyte** [comment]
Change `mysql` to `mysqli`. Done. MySQLi works fine in PHP7.x

**Comment by jhohorst** [comment]
I'm just running into this as well - when you say "Change mysql to mysqli", are you talking about in the line in qbwc_config.php:

//	Database Connection String
	$dsn = 'mysqli://...

If so, it's a pretty easy switch.
