### ISSUE TITLE
how to get the token and oauth_consumer_key and oauth_consumer_secret 

### ISSUE THREAD

**Issue by sunilyadavacs** [consolibyte/quickbooks-php#214]
how to get the token and oauth_consumer_key and oauth_consumer_secret

**Comment by consolibyte** [comment]
OAuth consumer key and consumer secrets are for OAuth v1.0. You should be using OAuth v2.0 from this point forward (and thus a client ID and client secret). 

Log in to developer.intuit.com and click MY APPS to get these.
