### ISSUE TITLE
Slow loading of invoice service query

### ISSUE THREAD

**Issue by fleetclean** [consolibyte/quickbooks-php#220]
Is there any way to speed up the SQL call using the `QuickBooks_IPP_Service_Invoice` class? It takes at least 30 seconds to load 50 invoices in a table.

**Comment by consolibyte** [comment]
Did you benchmark things, to determine specifically what part of things is slow? 

Is it the actual code? Or is it the actual QuickBooks API call that's slow? What's your code look like?
