### ISSUE TITLE
Dsn format doesn't seem work anymore

### ISSUE THREAD

**Issue by tnguyen444** [consolibyte/quickbooks-php#221]
I am using the dsn string of:

`mysqli://thisismyuser:thisismypassword@thisismyhost/thisismydb`

And it doesn't seem to work anymore? Seems like it's not extracting the scheme correctly?

**Comment by consolibyte** [comment]
Works fine for me. 

Specifically what error message are you getting? 
Can you give a specific example I can use to reproduce the issue?

**Comment by tnguyen444** [comment]
Sorry, I meant to say, the password is something like this: this#is#my#password
Looks like it's due the password with special characters causing parse_url() not to work as intended.  The odd thing is, this was working before an  I have not changed php versions or passwords.

**Comment by consolibyte** [comment]
The password will need to be URL encoded. Is it?

**Comment by tnguyen444** [comment]
Looks like that works! Thansk! Still don't understand why this suddenly became and issue though.
