### ISSUE TITLE
OAuth 1 Deprecation - IS OAuth 2 Available?

### ISSUE THREAD

**Issue by whobutsb** [consolibyte/quickbooks-php#227]
Just received an email from Quickbooks saying that OAuth version 1 was being deprecated.  Does this package support OAuth version 2?  Is there any changes that need to be made in my current codebase to use it, is there any update instructions available? 

Thank you advance.

**Comment by Jxckaroo** [comment]
Hey,

I think this may be what you are looking for: [OAuth2 support #205](https://github.com/consolibyte/quickbooks-php/pull/205)

Looks like they are trying to get it working :)

**Comment by consolibyte** [comment]
The 3.6 release has working OAuth v2.0 support now. OpenID Connect and an automated OAuth v1 to v2 migration process are coming soon.

https://github.com/consolibyte/quickbooks-php/releases/tag/v3.6

Manual migration (e.g. you have to reconnect via the OAuth flow) instructions are here:
https://github.com/consolibyte/quickbooks-php/blob/master/README_OAUTHV1_TO_OAUTHV2.md

ALSO -- Migrate your app to OAuth 2.0 before May 31 and you could win a limited edition Intuit hoodie, PLUS if you tell Intuit about your migration plans, you’ll gain entry to win the entertainment system of your dreams. Find out more here: https://intuit.me/OAuth2
