### ISSUE TITLE
$dsn not parsing properly

### ISSUE THREAD

**Issue by calhounpaul** [consolibyte/quickbooks-php#231]
I got around it by commenting this out from utilities.php:
`$parse = array_merge($defaults, parse_url($dsn));`
and then manually creating the $parse array from the various components of my $dsn:
`		$parse = array(`
`			'scheme' => 'mysqli', `
`			'host' => '[host url]', `
`			'port' => 3309, `
`			'user' => '[username]', `
`			'pass' => '[pass]', `
`			'path' => '/databasename', `
`			'query' => '', `
`			'fragment' => '', `  
`			);`
It probably screws something up elsewhere. I'm new to this.

**Comment by consolibyte** [comment]
Does your password have any special characters in it? Anything that's not a letter or a number?

**Comment by calhounpaul** [comment]
OH!!!
I've learned a valuable lesson.

**Comment by calhounpaul** [comment]
Looks like there was a hash symbol that was doing it: https://bugs.php.net/bug.php?id=73754
The fix is to html encode it as %23
