### ISSUE TITLE
Loader is broken

### ISSUE THREAD

**Issue by fleetclean** [consolibyte/quickbooks-php#238]
I get these errors when calling the autoloader. I recently upgraded to PHP 7.3.1 and Apache 2.4.37.

ERROR - 2019-01-22 08:56:06 --> Severity: Warning  --> array_merge(): Expected parameter 2 to be an array, bool given /var/www/html/dev_daniel/plugins/QuickBooks/Utilities.php 54
ERROR - 2019-01-22 08:56:06 --> Severity: Notice  --> Undefined index: pass /var/www/html/dev_daniel/plugins/QuickBooks/Utilities.php 57
ERROR - 2019-01-22 08:56:06 --> Severity: Warning  --> require_once(/var/www/html/dev_daniel/plugins/QuickBooks/Driver/.php): failed to open stream: No such file or directory /var/www/html/dev_daniel/plugins/QuickBooks/Loader.php 56

**Comment by consolibyte** [comment]
Did you specify a password in your $dsn string? 

It looks like you have an invalid $dsn connection string, but it's difficult to tell without you posting some context here.

**Comment by consolibyte** [comment]
Can you post an example (obviously don't include the real password) of your $dsn string? It looks like it's not being parsed correctly. 

Are there any special characters (non- A-Z0-9) in the username or password?

**Comment by fleetclean** [comment]
mysqli://user:xxxxxxxx#xxxxxxxxxxxxxxx@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.rackspaceclouddb.com/db_name

The password has a '#' character in it.

**Comment by consolibyte** [comment]
Did you `urlencode` the password, like you have to for URLs?

**Comment by fleetclean** [comment]
The `parse_url` function in Quickbooks/Utilities.php on line 54 is returning false causing the `$parse` variable to be empty.

**Comment by consolibyte** [comment]
OK, so something in your $dsn string is badly formatted then. You're SURE there's no other non- A-Z0-9 characters in the username/password/database name/host/etc. ?

**Comment by fleetclean** [comment]
The username and database both have a '_' character. The password has a '#' character in it.

**Comment by consolibyte** [comment]
So this is what I would recommend -- try to get just php.net/parse_url to work stand-alone. My bet is your $dsn string is not formatted as a valid URL. 

You have to `urlencode` each individual component of the URL. e.g. you can't just `urlencode($dsn)`  you have to `urlencode` the password, and then concat to the `urlencode` username, and then ...
