### ISSUE TITLE
QuickBooks Desktop Enterprise 18 Customer add problem

### ISSUE THREAD

**Issue by moumita-ray** [consolibyte/quickbooks-php#246]
I'm using the SDK provided at https://github.com/consolibyte/quickbooks-php. My object is to add customer to QB desktop edition using a XML(SOAP request).

The code I'm following is https://github.com/consolibyte/quickbooks-php/blob/master/docs/web_connector/example_web_connector.php. The only changes I've done,
1. DSN, **$dsn = 'mysqli://root:@localhost/quickbooks_sqli';**
2. Web connector,

<?xml version="1.0"?>
<QBWCXML>
	<AppName>QuickBooks - Codaemon Add Customer Integrator</AppName>
	<AppID></AppID>
<AppURL>http://localhost/qbsoapserver/docs/web_connector/example_web_connector.php</AppURL>
	<AppDescription></AppDescription>
<AppSupport>http://localhost/qbsoapserver/docs/web_connector/example_web_connector.php?support=1</AppSupport>
	<UserName>quickbooks</UserName>
	<OwnerID>{60A44FB7-33D9-4815-AC85-AC86A7E7D1EG}</OwnerID>
	<FileID>{47F3B9B6-86F1-4fcc-B1FF-967DE1813D28}</FileID>
	<QBType>QBFS</QBType>
	<Scheduler>
		<RunEveryNMinutes>5</RunEveryNMinutes>
	</Scheduler>
	<IsReadOnly>false</IsReadOnly>
</QBWCXML>

I've followed the forum for ideas. As per your answers which I found in the forum, I've cleared the two tables `quickbooks_queue` and `quickbooks_recur`. When I'm running the web connector it's not giving any error.

Version: PHP QuickBooks SOAP Server v3.0 at /qbsoapserver/docs/web_connector/example_web_connector.php
Message:
No data exchange required
Description:
No data to exchange for this application. Job ending.
But whenever trying to run in the URL or postman not getting any positive response for adding customer from the XML to QB desktop showing flowing :
Use the QuickBooks Web Connector to access this SOAP server.
QuickBooks_WebConnector_Server::handle() parameters: 
 - $return = 1
 - $debug  = 1
Misc. information: 
 - Logging: 3
 - Timezone: America/New_York (Auto-set: )
 - Current Date/Time: 2019-05-16 02:54:23
 - Error Reporting: 327
SOAP adapter: 
 - QuickBooks_Adapter_Server_Builtin
Registered handler functions: 
Array
(
    [0] => __construct
    [1] => authenticate
    [2] => sendRequestXML
    [3] => receiveResponseXML
    [4] => connectionError
    [5] => getLastError
    [6] => closeConnection
    [7] => serverVersion
    [8] => clientVersion
)
Detected input: 
Timestamp: 
 - 2019-05-16 02:54:23 -- process 0.09627
OR
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

Please guide us how to reach to our goal. We're stuck and trying to debug using every possible help available over internet.

**Thanks**

**Comment by consolibyte** [comment]
It doesn't look like you're getting any errors here. It looks like you have "No data exchange required" (e.g. you haven't told QB to add anything). 

Post your code. What did you queue up to be added?

**Comment by moumita-ray** [comment]
Thanks for your response, here is my code,
1. qbsoapserver\docs\web_connector\example_web_connector.qwc, web connector file
2. qbsoapserver\docs\web_connector\example_web_connector.php, php file to put the SOAP request

Please guide us how to tell QB to add customer, we're trying to apply using the code available over internet, do we need to modify anything? Our objective is to add/edit/retrieve data from QB desktop to web using SOAP.

**Comment by moumita-ray** [comment]
Thanks for your reply, my code is uploaded at https://github.com/moumita-ray/-quickbookapp
Both the files https://github.com/moumita-ray/-quickbookapp/blob/master/web_connector/example_web_connector_queueing.php and https://github.com/moumita-ray/-quickbookapp/blob/master/web_connector/example_web_connector.php was used for the customer add

**Comment by consolibyte** [comment]
Are you following the quick-start guide? 
https://github.com/consolibyte/quickbooks-php#quick-start-guides

It looks like you've somehow merged the queuing file, with the web connector server...?  I think you should probably start fresh here, and make sure you're following the quick-start guide and can get that to work.

**Comment by moumita-ray** [comment]
Hi,

Thanks for your help, it's working.
