### ISSUE TITLE
Import customer from QB to MySQL

### ISSUE THREAD

**Issue by moumita-ray** [consolibyte/quickbooks-php#248]
Hi, 
My codes are available at the link https://github.com/moumita-ray/quickbooks-xml/.
I'm facing some problem when trying to import customer from our QB to MySQL database.
My web connector file is https://github.com/moumita-ray/quickbooks-xml/blob/master/customer_import.qwc and the php file is https://github.com/moumita-ray/quickbooks-xml/blob/master/customer_import.php.
 When I'm running the code in web connector I'm getting the following error,
--------------------------------------------------------------------------------------
Version:
PHP QuickBooks SOAP Server v3.0 at /quickbooks-xml/customer_import.php

Message:
ReceiveResponseXML failed

Description:
QBWC1042: ReceiveResponseXML failed
Error message: Response is not well-formed XML. See QWCLog for more details. Remember to turn logging on.
--------------------------------------------------------------------------------------
How to resolve the issue, am I walking on the correct track?
What will be change if I want to add/update a set of customer with particular parameters given (eg. date range)?

Kindly help me on this.

**Comment by consolibyte** [comment]
This is almost always a PHP or SQL error. Did you check your PHP error logs?

**Comment by moumita-ray** [comment]
There was some MySQL connection related issue which I resolved and run code again on WC. Now the data is transferred but throwing some error, 3391: The iteratorID "{714f5c57-6d79-4d1c-ad70-a786caa2231f}" is not valid. I have checked the Apache error log, but nothing related error was there, I checked the WC error log also. Can you give me any hint for what it's causing an error?

**Comment by moumita-ray** [comment]
Sometimes its showing Complete in web connector,

Version:
PHP QuickBooks SOAP Server v3.0 at /quickbooks-xml/customer_import.php

Message:
Complete!

Description:
Via closeConnection(): CloseConnection called to application.
Response received from application = Complete!

I'm not getting any clue what is causing error 3391: The iteratorID "{714f5c57-6d79-4d1c-ad70-a786caa2231f}" is not valid.

**Comment by consolibyte** [comment]
Here's where to get support:
https://github.com/consolibyte/quickbooks-php#support

Make sure you _post your code_.
