### ISSUE TITLE
Facing problem regarding 'QB_QUICKBOOKS_MAX_RETURNED' when imoprting data from QB to DB

### ISSUE THREAD

**Issue by moumita-ray** [consolibyte/quickbooks-php#249]
Hi Keith,
I was trying to import customer data from QB to db using XML. I am getting 'Complete!' message while running my qwc file through web connector. The problem I'm facing I'm providing below,

1. There is total 67 records in Quickbooks, but we are getting only 60 records in local DB after running the file in web connector.
2. If I increase the QB_QUICKBOOKS_MAX_RETURNED to 100 or something else for the first time when importing data, records are not coming in MySQL db. We can have much more records in QB, so what is the solution should be here.
3. All the records we are importing into db is having IsActive value 0 in MySQL db.

We are very near to our success point but can't reach to it. Please guide us with your suggestion.

My code bunch is available at github, the qwc file is located at _**https://github.com/moumita-ray/quickbooks-xml/blob/master/customer_import.qwc**_ and the php file is at _**https://github.com/moumita-ray/quickbooks-xml/blob/master/customer_import.php**_

**Comment by consolibyte** [comment]
Here's how to get support: 
https://github.com/consolibyte/quickbooks-php#support

GitHub is not the place to post issues with your own code.
