### ISSUE TITLE
Migration from oAuth 1.0 to oAuth 2.0

### ISSUE THREAD

**Issue by danieleperilli** [consolibyte/quickbooks-php#250]
First of all, thanks for your great job!

I just want to highlight some minor issues in the migration documentation:
- `Code change - IntuitAnywhere->load(...)` -- You didn't remove $the_username from the second method
- `Code change - IntuitAnywhere->check(...)` -- Same as before
- `Code change - IntuitAnywhere->test(...)` -- You didn't put $the_username in the first method
Moreover, you missed to report the changes in the ->handle() and ->disconnect() methods.

**Comment by ahmadnawaz121** [comment]
Any updates on this? Is Disconnect working in its current state?

**Comment by ve7tcc** [comment]
> Any updates on this? Is Disconnect working in its current state?

Have a look at pull request #273
I added code to allow you to do $IntuitAnywhere->disconnectV2($the_tenant);

Duncan

**Comment by gsalmon-credz** [comment]
So much of this library has not been updated to support the OauthV2 changes. EG most of IPP/Services

**Comment by Blkc** [comment]
> So much of this library has not been updated to support the OauthV2 changes. EG most of IPP/Services

oAuth2 mostly affects the authentication on each call, the underlying resources are not changed. We built our own abstraction layer with our own tables for storing the tokens and expiry dates, and use that to call the resources using this library. It works fine so far for most of the resources.
