### ISSUE TITLE
Payments and OAuthV2

### ISSUE THREAD

**Issue by dvelopin** [consolibyte/quickbooks-php#252]
I just migrated a web application from OAuthV1 to OAuthV2 and have been able to reconnect QuickBooks. However, now when trying to process payments I am having issues:

1) IPP/Payments.php was not updated to load OAuthv1.php instead still loads old OAuth.php which results in an error.

2) Once updating this or simply copying OAuthv1.php to Auth.php and uploading this, the system then looks for class QuickBooks_IPP_OAuth and not QuickBooks_IPP_OAuthv1, so I updated the class name.

These couple changes helped move things forward again. Now however I am receiving the following when trying to process a payment:

-2001: Communication error while processing request.

Looking at the request going out to QuickBooks, it looks like this is still using OAuth1:

`POST https://sandbox.api.intuit.com/quickbooks/v4/payments/charges HTTP/1.1
Content-Type: application/json
Request-Id: REDACTED
Authorization: OAuth realm="",  oauth_signature_method="HMAC-SHA1",  oauth_signature="REDACTED",  oauth_nonce="REDACTED",  oauth_timestamp="1559163660", oauth_token="REDACTED", oauth_consumer_key="REDACTED",  oauth_version="1.0"
Content-Length: 316`

How can we update Payments.php to use OAuthV2?

**Comment by emilebourquin** [comment]
Has there been any development on the QuickBooks Payments side to update to OAuthV2? December 17th is coming up, and we need to have both working.

**Comment by consolibyte** [comment]
Latest version of the code does support the new APIs.
