### ISSUE TITLE
Error while using disableUser function

### ISSUE THREAD

**Issue by jayantsr83** [consolibyte/quickbooks-php#255]
I am using disableUser function to disable the existing user but at the time of using it, it throws following error

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function QuickBooks_Driver_Sql_Mysqli::_query(), 1 passed in /home/cobaltconnect/public_html/dev/user/cc-quickbooks/QuickBooks/Driver/Sql.php on line 700 and at least 3 expected in /home/cobaltconnect/public_html/dev/user/cc-quickbooks/QuickBooks/Driver/Sql/Mysqli.php:689 Stack trace: #0 /home/cobaltconnect/public_html/dev/user/cc-quickbooks/QuickBooks/Driver/Sql.php(700): QuickBooks_Driver_Sql_Mysqli->_query('\r\n\t\t\tUPDATE\r\n\t\t...') #1 /home/cobaltconnect/public_html/dev/user/cc-quickbooks/QuickBooks/Driver.php(1333): QuickBooks_Driver_Sql->_authDisable('Colony Diner') #2 /home/cobaltconnect/public_html/dev/user/cc-quickbooks/QuickBooks/Utilities.php(907): QuickBooks_Driver->authDisable('Colony Diner') #3 /home/cobaltconnect/public_html/dev/user/inc/profile.php(8): QuickBooks_Utilities::disableUser('mysqli://cobalt...', 'Colony Diner') #4 /home/cobaltconnect/public_html/dev/user/index.php(220): include('/home/cobaltcon...') #5 {main} thrown in /home/cobaltconnect/public_html/dev/user/cc-quickbooks/QuickBooks/Driver/Sql/Mysqli.php on line 689`

and this is how i am using this function

`$dsn = 'mysqli://username:'.urlencode('passwordhere').'@localhost/dbname';
	
QuickBooks_Utilities::disableUser($dsn,$qb_username);`

**Comment by mreiden** [comment]
I started a fork to get this library to use namespaces, but I ran across this issue after adding tests for QuickBooks_Utilities::enableUser and QuickBooks_Utilities::disableUser.

This is fixed by PR https://github.com/consolibyte/quickbooks-php/pull/264.

I hope to push my namespaces branch after adding more tests.  I don't use QB Online, so I could use help testing.

**Comment by consolibyte** [comment]
This PR was merged.
