### ISSUE TITLE
3140: Invalid Reference to QuickBooks Customer

### ISSUE THREAD

**Issue by leech-coder** [consolibyte/quickbooks-php#256]
![QBWebConnector_NR8iyNa4kB](https://user-images.githubusercontent.com/51350478/58999915-c8cefd80-883a-11e9-8730-7b7d6e9d3d68.png)

The queuing order of our data to QuickBooks is:
1. CustomerAdd
2. ItemNonInventoryAdd
3. InvoiceAdd

For some reason, the Web Connector syncs the Invoice before the Customer which returns the invalid reference error.

![chrome_5Y3M2KIYI6](https://user-images.githubusercontent.com/51350478/59000013-2cf1c180-883b-11e9-9e23-589b70250b81.png)

The leftmost column is the `quickbooks_queue_id`.

**Comment by leech-coder** [comment]
The same thing happens with ItemNonInventoryAdd; the Web Connector syncs the InvoiceAdd before the ItemNonInventoryAdd.

> _3140: There is an invalid reference to QuickBooks Item in the Invoice line. The specified record does not exist in the list._

This seems to be random. Some Invoice appear successfully on QuickBooks Desktop.

**Comment by consolibyte** [comment]
To me it looks like the priority on each of those is `0`, correct?

Which means the order that things process in is essentially random. 

Did you set priorities for each of those queued items?

**Comment by leech-coder** [comment]
> To me it looks like the `priority` on each of those is `0`, correct?

Thanks for pointing that out. I was solely relying on the `quickbooks_queue_id`.
