### ISSUE TITLE
Desktop Soap Error VersionMismatch(Wrong Version)

### ISSUE THREAD

**Issue by ajaygiri97** [consolibyte/quickbooks-php#257]
Hello,

I am using PHP version 7.0 and greater. I am trying to connect with quickbook Desktop application using your git code

https://github.com/consolibyte/quickbooks-php

I am getting version error.

`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Body>
        <SOAP-ENV:Fault>
            <faultcode>SOAP-ENV:VersionMismatch</faultcode>
            <faultstring>Wrong Version</faultstring>
        </SOAP-ENV:Fault>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

I think may be soap version error. Coud you please provide me saop version 1.2 WSDL?

**Comment by mreiden** [comment]
Try this and let us know if it worked: https://test.developer.intuit.com/QBWC/TroubleshootWebServiceFS/Service.asmx?wsdl
