### ISSUE TITLE
Update quickbook desktop invoice issue

### ISSUE THREAD

**Issue by sapangupta2009** [consolibyte/quickbooks-php#266]
Hey,
I want to sync updated invoice data like amount, status, etc to quickbook but when I am doing so, the quickbook desktop overwrites the invoice with old information first and my update doesn't work. 

Would you please help me with this?

**Comment by consolibyte** [comment]
You will need to post your code / show us what you're doing if you need help. Highly recommend posting general help questions like this on StackOverflow.
