### ISSUE TITLE
Continue even after no matching object

### ISSUE THREAD

**Issue by rahilwazir** [consolibyte/quickbooks-php#267]
When I run iterator for second time, it outputs the following error on QWC

> A query request did not find a matching object in QuickBooks Desktop Point of Sale

I believe this is due to there are no items exists in the current and last time duration, which makes sense. But I don't want the queue to exit out with the error. But instead it should continue to next scheduled job.

This is XML request body

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?qbposxml version="3.0"?>
<QBPOSXML>
	<QBPOSXMLMsgsRq onError="continueOnError">
		<DepartmentQueryRq iterator="Start">
			<MaxReturned>5</MaxReturned>
			<TimeModifiedFilter>
				<MatchNumericCriterion>GreaterThanEqual</MatchNumericCriterion>
				<TimeModified>2019-07-12T15:39:03</TimeModified>
			</TimeModifiedFilter>
		</DepartmentQueryRq>
	</QBPOSXMLMsgsRq>
</QBPOSXML>
```

Now there are no items that has been modified since `2019-07-12T15:39:03` thus it outputs the error mentioned above.
I have the error map `*` to catch all errors.

**Comment by rahilwazir** [comment]
Ok I found the solution. The error map function needs to return true in order to continue it to the next scheduled iterator.

```php
function _quickbooks_error_catchall($requestID, $user, $action, $ID, $extra, &$err, $xml, $errnum, $errmsg)
{
    ...
    ...

    return true; // continue if true, otherwise stop if false
}
```

**Comment by michaelhall923** [comment]
Thank you you saved my life.
