### ISSUE TITLE
<RefNumber> - Element content is invalid according to the DTD/Schema (qbValidator)

### ISSUE THREAD

**Issue by leech-coder** [consolibyte/quickbooks-php#275]
> ### How can I set the invoice number for an invoice?
> You can set the invoice number for an invoice by setting the
> ```xml
>  <RefNumber>...</RefNumber>
> ```
> tag in your qbXML InvoiceAddRq or InvoiceModRq. The returned TxnID tag is auto-generated by QuickBooks and cannot be set, but the RefNumber will be the one displayed in the QuickBooks GUI.

<sub>SRC: [QbXML_FAQ](http://www.consolibyte.com/docs/index.php/QbXML_FAQ)</sub>

`qb*XML Validator` keeps returning 'invalid element content' whenever I add a `RefNumber`. Changing the order within the XML only adds/removes **`Expecting`** _`<element(s)>`_.

```xml
<?xml version="1.0" encoding="utf-8"?>
<?qbxml version="2.0"?>
<QBXML>
	<QBXMLMsgsRq onError="continueOnError">
        <InvoiceAddRq requestID="requestID"> 
            <RefNumber>0123456789</RefNumber>    
            <InvoiceAdd>
        	<CustomerRef>
          	   <FullName>John Doe</FullName>
                </CustomerRef>
                <TxnDate>2019-09-11</TxnDate>
                <BillAddress>
                    <Addr1>123 St.</Addr1>
                    <Addr2></Addr2>
                    <City>Los Angeles</City>
                    <State>CA</State>
                    <PostalCode>90001</PostalCode>
                </BillAddress>
                <PONumber>123</PONumber>
                <Memo>Memo</Memo>
                <InvoiceLineAdd></InvoiceLineAdd>
      		</InvoiceAdd>
    	</InvoiceAddRq>
  	</QBXMLMsgsRq>
</QBXML>

```

**Comment by consolibyte** [comment]
Please refer to the QuickBooks OSR for the correct order of elements, and use the qbXML Validator. 

You'll see that the `RefNumber` tag should be _inside_ the `InvoiceAdd` section. Also, you're using a version of qbXML that is 17 years old (2.0) so you may want to update that while you're at it.
