### ISSUE TITLE
QuickBooks Payments Service legacy SDK will expire on November 12th

### ISSUE THREAD

**Issue by drupalaid** [consolibyte/quickbooks-php#281]
Hi,
I just received the following from Intuit:
"Our legacy SDK will expire on November 12th and if you are continuing to use that application then your payments service will stop working on that date. ", "In order to continue processing payments, you need to update the application you are using to the latest QuickBooks Merchant Services API."

Is this library using the latest QuickBooks Merchant Services API?

**Comment by consolibyte** [comment]
Latest version of the code does support the new APIs.
