### ISSUE TITLE
Latest IntuitAnywhere.php confuses v1 and v2 on disconnect/reconnect

### ISSUE THREAD

**Issue by sandstones** [consolibyte/quickbooks-php#282]
In IntuitAnywhere.php the functions "expiry", "reconnect", "disconnect" all call 
    $this->_driver->oauthLoad(...).

However oauthLoad() does not exist, there is now oauthLoadv1() and oauthLoadv2().  

I originally thought the calls should call oauthLoadv1 because of references to v1 column names such as auth_request_token_secret.  

That removes errors, but disconnecting from a v2 oauth does nothing.

What should this look like?

**Comment by ve7tcc** [comment]
Have a look at PR #273 

I added a  $IntuitAnywhere->disconnectV2($the_tenant)

expiry is done differently.

Also check out #277

**Comment by silviusarmasanu** [comment]
I looked for the function $IntuitAnywhere->disconnectV2($the_tenant) , and I didn't find it. 
Can you help me with this update?

**Comment by ve7tcc** [comment]
Click the links in my original comment, then click on files changed to see the changes.

**Comment by consolibyte** [comment]
A commit has been made which fixes the `disconnect` method. 

It _removes_ the `reconnect()` method which is not needed for OAuthv2.
