### ISSUE TITLE
How to add attachment in the QuickBook PHP-SDK ?

### ISSUE THREAD

**Issue by antonyanand** [consolibyte/quickbooks-php#284]
My code is,

       $attachment = "/Users/processdrive/Downloads/export.pdf";

        $sendMimeType = mime_content_type($attachment);

        $randId = rand();
        $entityRef = new IPPReferenceType(array('value'=> '154', 'type'=>'Invoice'));
        
        $attachableRef = new IPPAttachableRef(array('EntityRef' => $entityRef));
        $objAttachable = new IPPAttachable();
        $objAttachable->FileName = basename($attachment);
        $objAttachable->AttachableRef = $attachableRef;
        $objAttachable->Tag = 'Tag_' . $randId;

        // // Upload the attachment to the Bill
        $resultObj = $dataService->Upload($attachment,
        $objAttachable->FileName,
        $sendMimeType,
        $objAttachable);

Here the attachment is adding to the Invoice. But when previewing the uploaded file it is showing following error.

![Screen Shot 2019-12-10 at 12 47 31 PM](https://user-images.githubusercontent.com/37414962/70504306-85d44680-1b4b-11ea-8281-19f5aed91708.png)

Can anyone help me out ?

**Comment by riversevilla** [comment]
Hi there @antonyanand, my team is having the same issue. Attachments can be previewed before, but suddenly we're now getting the same error. This is a bit late, but were you able to find a solution to this?
