### ISSUE TITLE
Oauth2 no way to reconnect on failed login

### ISSUE THREAD

**Issue by aik099** [consolibyte/quickbooks-php#285]
I'm trying to login, but oauth2 access token, that QuickBooks issued apparently has been revoked (even though it only has 1 hour expiration). In such scenario I have no method to call, that will prolong access token considering that oauth2 refresh token might still be valid.

For oauth1 I've used `reconnect` method, but it doesn't support oauth2.

What should I do?

**Comment by aik099** [comment]
Debugging revealed issue with `\QuickBooks_IPP::_handleRenewal` method, that considered access token as non-expired 1 minute after it was already expired and wasn't renewing it automatically.

I'll send a PR shortly.

**Comment by consolibyte** [comment]
You may want to `git pull` here. There was another merge last week and some additional changes this week which should have addressed this already.

**Comment by consolibyte** [comment]
https://github.com/consolibyte/quickbooks-php/blob/master/QuickBooks/IPP.php#L871

**Comment by aik099** [comment]
Yes, I can see, that it was addressed, but not released. I'll use `master` branch then.
