### ISSUE TITLE
consolibyte quickbooks oauth1 to oauth2 migration issue

### ISSUE THREAD

**Issue by imran-khan-sahil** [consolibyte/quickbooks-php#290]
Hi,
I am migrating already implemented consolibyte/quickbooks oauth1 in laravel 4.2 and php version 5.5.33 but now I am migrating it to oauth2 without re-installing consolibyte/quickbook I changed my controller or library using this guide line:
https://github.com/consolibyte/quickbooks-php/blob/master/README_OAUTHV1_TO_OAUTHV2.md
I am facing these issues:
1- After re-connecting with quickbook my oauth2 table is still empty.
2- If I insert the oauth2 data in table by my self this error is comming:

ERROR: [object] (ErrorException(code: 0): unserialize(): Error at offset 0 of 543 bytes at /home/www/staging.neon.service/vendor/consolibyte/quickbooks/QuickBooks/Encryption/Aes.php:82

1- Do I need to re install the consolibyt/quickbook?
2- Do I need to update the apache version?
Please quide me how to fix this issue

**Comment by imran-khan-sahil** [comment]
Hi,

I am working on urgent piece of work so, please update me.

Thanks

**Comment by saadishtiaq** [comment]
Experiencing same problem any solution?

**Comment by ebogdanov** [comment]
> Experiencing same problem any solution?

Check this out - https://github.com/consolibyte/quickbooks-php/issues/286
