### ISSUE TITLE
Why disconnect no longer needed?

### ISSUE THREAD

**Issue by jburgoyn** [consolibyte/quickbooks-php#291]
I see in the migration guide that it says the disconnect() method is no longer needed for oauth2 but this doesn't make sense to me. The users should still be able to disconnect from a web app via the web app, and this is a requirement for apps on the QBO App Store.

Has anyone successfully performed a disconnect using this library?

**Comment by consolibyte** [comment]
This is a mistake in the documentation. `->disconnect($tenant)` is still supported, and works fine. 

I will fix the migration guide/documentation.

**Comment by jburgoyn** [comment]
Thanks a ton! Got it working too.
