### ISSUE TITLE
Data exchange between two different quickbooks companies

### ISSUE THREAD

**Issue by mohit-dexbytes** [consolibyte/quickbooks-php#319]
We use QuickBooks web connector to sync between QuickBooks desktop and our web application for multiple customers. The architecture we are following is as follows:

Web Application/Customer1 -> quickbooks-php-application -> Quickbooks Desktop (Customer1)
Web Application/Customer2 -> quickbooks-php-application -> Quickbooks Desktop (Customer2)
Web Application/Customer3 -> quickbooks-php-application -> Quickbooks Desktop (Customer3)

We have a different QuickBooks user name for each customer ( i.e. each QWC has a different user name )

It works well when one customer is syncing at one time, but when multiple customers sync at the same time, their data gets interchanged i.e. few invoices of customer1 are syncing to customer2 and vice versa.

Please let me know what the solution to this issue is.

**Comment by bportman** [comment]
I'm wondering about this as well - it seems like the safe bet is to use a separate instance of the PHP application for each customer, with a separate database.  I'm looking for a way to scale this approach, though.

**Comment by mohit-dexbytes** [comment]
Here the culprit is **QuickBooks_WebConnector_QWC::GUID(false);**. When multiple users initialize the sync using a web connector at the same time (even with second and milli seconds) then GUID returns the same string for the multiple users, which leads to a duplicate ticket in the **quickbooks_ticket** table, and the data interchanged between Customer1 & Customer2.

I preferred to create a ticket using the timestamp with username to avoid such a case.
`$ticket = md5((string) microtime() . $username);`

Code & Issue can be found here: https://github.com/consolibyte/quickbooks-php/blob/8ecf38012c330568d661458eb82c5788252d8212/QuickBooks/Driver/Sql.php#L875
