### ISSUE TITLE
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future

### ISSUE THREAD

**Issue by diaspar** [consolibyte/quickbooks-php#47]
I am getting this warning with php 5.5

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in vendor/consolibyte/quickbooks/QuickBooks/Driver/Sql/Mysql.php on line 289

**Comment by moiz-frost** [comment]
I was wondering that since changing the scheme to mysqli, how will I be able to call mysqli_query without the $link parameter?
