### ISSUE TITLE
Add support for Sandbox

### ISSUE THREAD

**Issue by aik099** [consolibyte/quickbooks-php#48]
In QuickBooks it's possible to enable sandbox mode. In that case URL for API is a bit different (the `sandbox-` is added in front of domain it seems.

Please allow for setting base url externally instead of hardcoding it in here:  https://github.com/consolibyte/quickbooks-php/blob/master/QuickBooks/IPP.php#L993

**Comment by keithslater** [comment]
I added support for this and created a pull request https://github.com/consolibyte/quickbooks-php/pull/52

**Comment by aik099** [comment]
Thanks. Now we'll wait for it to be merged and new release tagged.

**Comment by consolibyte** [comment]
$IPP->sandbox(true); Examples in latest.

**Comment by aik099** [comment]
I'm certain, that there was no such method, when I've created this ticket and when @keithslater added his #52 PR.

**Comment by aik099** [comment]
The https://github.com/consolibyte/quickbooks-php/commit/91723f26887604afa24187922f90e8cea7b17f28 commit is 100% copy of #52 PR. Why just not merge the PR to preserve @keithslater attribution (commit author)?

**Comment by consolibyte** [comment]
No, it is absolutely not. Please look again. 

We had this in the works already, independently, prior to when the pull request came in.

**Comment by aik099** [comment]
I see, my apologies for not reviewing you commit from top to bottom.

At company I'm working in we needed to release project, that used this library so I was forced to use solution from that PR.

Are there any delays in PR processing expected in future (I've created task in 13 Nov 2014 and it was processed in Feb 12 2015)?

**Comment by consolibyte** [comment]
We'll try to get to these in a more timely manner -- been a little swamped lately.
