### ISSUE TITLE
Please update tag list on Packagist

### ISSUE THREAD

**Issue by aik099** [consolibyte/quickbooks-php#49]
The 3.0 version isn't shown on https://packagist.org/packages/consolibyte/quickbooks . Maybe repo's after commit hook that submits repo changes to Packagist is broken or tag name isn't in supported format.

**Comment by caseyw** [comment]
@consolibyte This would be awesome :) It's how all of the businesses I work with import packages now days.

**Comment by consolibyte** [comment]
Fixed now.
