### ISSUE TITLE
QuickBooks Online - ParentRef and jobs

### ISSUE THREAD

**Issue by keithslater** [consolibyte/quickbooks-php#54]
According to the Quickbooks Online documentation there should be a ParentRef for Customers which accepts a ReferenceType. I'm not seeing this in quickbooks-php.

Here's the relevant info from their API docs:

    ParentRef: 
    ReferenceType, default is null 
    The immediate parent of the Sub-Customer/Job in the hierarchical "Customer:Job" list. 
    Required for the create operation if the Customer is a sub-customer or Job.

**Comment by consolibyte** [comment]
$Customer->setParentRef($your_parent_id_value);

**Comment by panreach** [comment]
I had to also set the job to 1 for this to work.

$Customer->setJob(1);
