### ISSUE TITLE
Unable to query customer by ID

### ISSUE THREAD

**Issue by whobutsb** [consolibyte/quickbooks-php#55]
Hello I'm trying to use the method `findById()` in the `QuickBooks_IPP_Service_Customer` class.  I keep getting the error message: `Undefinied variable: url` on this line: https://github.com/consolibyte/quickbooks-php/blob/master/QuickBooks/IPP.php#L1022

The code that I'am running: 
```
// authentication already handled
$realm = $creds['qb_realm'];
if($Context = $IPP->context()){
    $CS = new \QuickBooks_IPP_Service_Customer();
    $customer = $CS->findById($Context, $realm, '{-1093}');
    var_dump($customer);
}
```

And just for my knowledge what do I pass for the ID in the customer? Is it: `1093`, `{QBO-1093}`, or `{-1093}`?  

Thanks for the help!

**Comment by whobutsb** [comment]
So I did just learn I can find Customers via the query() method.  Like so:

`$customer = $CS->query($Context, $realm, "SELECT * FROM Customer WHERE Id = '1093'");`

**Comment by zerolfc** [comment]
It seems the function `findById` does nothing. 

```php
$id = 77;
$CustomerService = new \QuickBooks_IPP_Service_Customer();
$customers = $CustomerService->findById($Context, $Realm, "{-$id}");

print_r($customers); //return empty
```

still have to use:
```php 
$CustomerService->query( $Context, $Realm, "SELECT * FROM Customer WHERE Id = '{$id}' ");
```

**Comment by whobutsb** [comment]
After reviewing, I believe the QuickBooks API was having issues and was causing the issues.
