### ISSUE TITLE
Does you library supports quickbooks 15 enterprise?

### ISSUE THREAD

**Issue by diaspar** [consolibyte/quickbooks-php#65]
Hey Keith.

Excellent library, we are using it to communicate our site with quickbooks enterprise (desktop) using the web connector.

I was wondering if we can continue using this library together with Quickbooks enterprise 15. Also we have this version locked with composer:

```
            "name": "consolibyte/quickbooks",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/consolibyte/quickbooks-php.git",
                "reference": "490ba8dff986faef57016194c3270ea4811c50d9"
            },
```

And we would like to know if we can continue using that version, because it's the one we used for all the communication tests.

**Comment by consolibyte** [comment]
We support *all* versions of QuickBooks 2003 and newer, including all years of Enterprise (and QuickBooks Online too).
