### ISSUE TITLE
Is support missing for QUICKBOOKS_REPORT_GENERAL_SUMMARY?

### ISSUE THREAD

**Issue by hemmerich** [consolibyte/quickbooks-php#66]
Is support missing for this type of request?

http://www.consolibyte.com/docs/index.php/QbXML_for_Reporting

I was not able to locate the proper action for this.

Thanks!

**Comment by consolibyte** [comment]
The constants are entirely optional. As long as what you use in $map matches what you use in $Queue->enqueue(...) you don't even need the constants. You can use any string you want, or define the constants yourself.

**Comment by hemmerich** [comment]
Thanks!



---

Daniel Hemmerich, CIO

WebpageFX, Inc.

Phone: 717.609.1698

Email: daniel@webpagefx.com



*From:* Keith Palmer [mailto:notifications@github.com]
*Sent:* Wednesday, July 1, 2015 9:30 AM
*To:* consolibyte/quickbooks-php
*Cc:* Daniel Hemmerich
*Subject:* Re: [quickbooks-php] Is support missing for
QUICKBOOKS_REPORT_GENERAL_SUMMARY? (#66)



The constants are entirely optional. As long as what you use in $map
matches what you use in $Queue->enqueue(...) you don't even need the
constants. You can use any string you want, or define the constants
yourself.

—
Reply to this email directly or view it on GitHub
<https://github.com/consolibyte/quickbooks-php/issues/66#issuecomment-117676685>
.
