### ISSUE TITLE
Is support included for importing inventory sites?

### ISSUE THREAD

**Issue by jweaver60** [consolibyte/quickbooks-php#70]
I'm trying to import inventory sites in my application, but there isn't a constant defined for that action. Is this something that can be done currently?

**Comment by consolibyte** [comment]
The constants aren't strictly required. As long as you make sure that the keys in $map match the action you use in $Queue->enqueue(...) then it'll work just fine. 

    $map = array(   'YeahInventorySites' => array( request function, response function ) );
    ...
    $Queue->enqueue('YeahInventorySites', ...)

**Comment by consolibyte** [comment]
Added these constants too.
