### ISSUE TITLE
Database SQL Dump

### ISSUE THREAD

**Issue by tavosansal** [consolibyte/quickbooks-php#75]
Hello,
I have tried to run the devkit mutiple times but every time I try to do it I keep getting errors about the database not being initialized (see below). I thought that the SDK was supposed to create the tables it needs automatically but it looks like that is not the case. I have tried multiple different database types as well (mysql, pgsql) with no luck both locally and on an external server (heroku). Would it be possible for someone to send me a SQL dump of the database that it is suppose to create for you? I feel like if I create it manually it will solve my problem since the errors I am getting are all about the tables not existing.

Query failed: ERROR: relation "quickbooks_log" does not exist LINE 3: quickbooks_log ^ in /app/vendor/consolibyte/quickbooks/QuickBooks/Driver/Sql/Pgsql.php on line 495 Fatal error: PostgreSQL Error: ERROR: relation "quickbooks_log" does not exist LINE 3: quickbooks_log ^, SQL: INSERT INTO quickbooks_log ( batch, msg, log_datetime ) VALUES ( 0, 'Handler is starting up...: array ( ''qb_company_file'' => NULL, ''qbwc_min_version'' => NULL, ''qbwc_wait_before_next_update'' => NULL, ''qbwc_min_run_every_n_seconds'' => NULL, ''qbwc_version_warning_message'' => NULL, ''qbwc_version_error_message'' => NULL, ''qbwc_interactive_url'' => NULL, ''autoadd_missing_requestid'' => true, ''check_valid_requestid'' => true, ''server_version'' => ''PHP QuickBooks SOAP Server v3.0 at /'', ''authenticate'' => NULL, ''authenticate_dsn'' => NULL, ''map_application_identifiers'' => true, ''allow_remote_addr'' => array ( ), ''deny_remote_addr'' => array ( ), ''convert_unix_newlines'' => true, ''deny_concurrent_logins'' => false, ''deny_concurrent_timeout'' => 60, ''deny_reallyfast_logins'' => false, in /app/vendor/consolibyte/quickbooks/QuickBooks/Driver/Sql/Pgsql.php on line 504

**Comment by consolibyte** [comment]
Please post your code so we can try to reproduce this.

**Comment by tavosansal** [comment]
Thank you for the reply.
I actually figured this out by looking at the logs of what the SQL statements are and piecing them together. Once I ran the SQL statements to create the right tables the DevKit ran just fine. If anyone is running into this issue, the SQL you need is here: https://gist.github.com/tavosansal/8dfc716c7a5aa50e52bb
