### ISSUE TITLE
QuickBooks_QBXML_Object_Invoice_SalesTaxLine::setRate calls itself, hanging PHP

### ISSUE THREAD

**Issue by scragz** [consolibyte/quickbooks-php#81]
[QuickBooks_QBXML_Object_Invoice_SalesTaxLine](https://github.com/consolibyte/quickbooks-php/blob/master/QuickBooks/QBXML/Object/Invoice/SalesTaxLine.php#L44) calls $this->setRate('Rate', $rate), probably should be $this->set('Rate', $rate);

**Comment by consolibyte** [comment]
Note that no one should be using this anyway, since it's only used in the legacy qbXML QBO implementation, which doesn't exist anymore. For QuickBooks desktop, you should use the ItemSalesTax node instead.
