### ISSUE TITLE
No old versions in Packagist

### ISSUE THREAD

**Issue by nathanharper** [consolibyte/quickbooks-php#83]
Would it be possible to put up older versions on Packagist? We're still on version 1.5.3 and aren't ready to make a full upgrade yet, but are trying to get the code out of our project and install it with composer.

**Comment by consolibyte** [comment]
I don't have the history to do this right now, but all versions going forward will be in Packagist now. The upgrade to 3.1 should actually be very, very easy. Send me an email if you need help migrating and I'll give you a hand.
