### ISSUE TITLE
Unable to query Invoice list

### ISSUE THREAD

**Issue by ravi3592** [consolibyte/quickbooks-php#90]
I am getting this error.

Warning:  require_once(C:\xampp\htdocs\projects\quick/QuickBooks\IPP\Object\DescriptionLineDetail.php): failed to open stream: No such file or directory in C:\xampp\htdocs\projects\quick\QuickBooks\Loader.php on line 56

Fatal error:  require_once(): Failed opening required 'C:\xampp\htdocs\projects\quick/QuickBooks\IPP\Object\DescriptionLineDetail.php' (include_path='.;C:\xampp\php\PEAR;C:\xampp\htdocs\projects\quick') in C:\xampp\htdocs\projects\quick\QuickBooks\Loader.php on line 56

**Comment by consolibyte** [comment]
This object has been added/commited to repo.
