### ISSUE TITLE
do_receiveResponseXML() not defining qbxml version

### ISSUE THREAD

**Issue by terryschwabl** [consolibyte/quickbooks-php#92]
```
20151104.22:39:20 UTC	: QBWebConnector.SOAPWebService.do_receiveResponseXML() : wcTicket="2a0185a1-95c8-a234-f927-c8705d69376b"
20151104.22:39:20 UTC	: QBWebConnector.SOAPWebService.do_receiveResponseXML() : response =
20151104.22:39:20 UTC	: QBWebConnector.SOAPWebService.do_receiveResponseXML() : XML dump follows: -

<?xml version="1.0" ?>
<QBXML>
<QBXMLMsgsRs>
<CustomerQueryRs requestID="241" statusCode="0" statusSeverity="Info" statusMessage="Status OK" iteratorRemainingCount="0" iteratorID="{84ff5521-205d-46b6-9d44-7b6b9acb7165}">
<CustomerRet>
<ListID>80000003-1446676743</ListID>
<TimeCreated>2015-11-04T14:39:03-08:00</TimeCreated>
<TimeModified>2015-11-04T14:39:03-08:00</TimeModified>
<EditSequence>1446676743</EditSequence>
<Name>abcde</Name>
<FullName>abcde</FullName>
<IsActive>true</IsActive>
<Sublevel>0</Sublevel>
<Balance>0.00</Balance>
<TotalBalance>0.00</TotalBalance>
<JobStatus>None</JobStatus>
<PreferredDeliveryMethod>None</PreferredDeliveryMethod>
</CustomerRet>
<CustomerRet>
<ListID>80000001-1446673838</ListID>
<TimeCreated>2015-11-04T13:50:38-08:00</TimeCreated>
<TimeModified>2015-11-04T14:39:10-08:00</TimeModified>
<EditSequence>1446676750</EditSequence>
<Name>Test Cust</Name>
<FullName>Test Cust</FullName>
<IsActive>true</IsActive>
<Sublevel>0</Sublevel>
<CompanyName>aaaa</CompanyName>
<BillAddress>
<Addr1>aaaa</Addr1>
</BillAddress>
<BillAddressBlock>
<Addr1>aaaa</Addr1>
</BillAddressBlock>
<Balance>123.00</Balance>
<TotalBalance>123.00</TotalBalance>
<JobStatus>None</JobStatus>
<PreferredDeliveryMethod>None</PreferredDeliveryMethod>
</CustomerRet>
</CustomerQueryRs>
</QBXMLMsgsRs>
</QBXML>


20151104.22:39:20 UTC	: QBWebConnector.SOAPWebService.do_receiveResponseXML() : hresult=""
20151104.22:39:20 UTC	: QBWebConnector.SOAPWebService.do_receiveResponseXML() : message=""
20151104.22:39:20 UTC	: QBWebConnector.SOAPWebService.do_receiveResponseXML() : QBWC1042: ReceiveResponseXML failed
Error message: Response is not well-formed XML.
```
This is the error I get in the web connector log. I think its because it doesn't have <?qbxml version="13.0"?> in the 2nd tag.

**Comment by consolibyte** [comment]
This error:
"Response is not well-formed XML."

Means you have a PHP or SQL error in your code. 

Check your PHP or SQL error log. Fix the error.

**Comment by rps-repo** [comment]
Hello!

 

You have a new message, please read <http://earningtimes.rlogical.com/again.php?4n>

 

tom@rapidach.com

**Comment by rps-repo** [comment]
Hi,

It is so exciting to tell you about what happened yesterday, you should better read it yourself <http://ltandiwefry.oneshortstory.com/aexsr>

Yours faithfully, tom@rapidach.com

**Comment by rps-repo** [comment]
Hello,

There is some helpful stuff I just found on the web, you may like it too, please read here <http://lifugyfra.cpeladecouverte.com/aelgo>

Best, tom@rapidach.com

**Comment by rps-repo** [comment]
Hi,

I've just seeen something very nice, it's so exciting, you have to take a look <http://kiraltivo.chadmcbrideandthedrifters.mobi/aemiuj>

Be well, tom@rapidach.com

**Comment by rps-repo** [comment]
Hello, 

Have you seen that news already? You're gonna be pleasantly surprised, read it here please <http://describe.revereagency.com/aecac>

Warm regards, tom

**Comment by rps-repo** [comment]
Hi! 

I  couldn't  decide which model of phone to buy so I decided to ask you, please take a look <http://expert.everestarrow.com/aeahr>


Warm regards, tom
~SUBJECT=need  your  advice
Hi! 

I've found  something interesting and need your opinion about that stuff, please take a  look  <http://expert.everestarrow.com/aeahr>

Warm regards, tom
