### ISSUE TITLE
Username and tenant

### ISSUE THREAD

**Issue by jaroslawziolkowski** [consolibyte/quickbooks-php#98]
I'm not sure, here
https://github.com/consolibyte/quickbooks-php/blob/master/docs/partner_platform/example_app_ipp_v3/config.php#L55
are $the_username, $the_tenant

does this variables are using only to get data from local database or also for API requests?

I need to save many tokens for my users and I think that this is correct way, but I'd like make sure.

**Comment by mryanb** [comment]
@jaroslawziolkowski Set `$the_tenant` to a unique ID of the users whos token you would like to store. You can then retrieve their tokens by referencing their `$the_tenant` ID.

**Comment by consolibyte** [comment]
See @mryanb's answer above. You do not need to change $the_username at all -- leave it static.
